[alias]
wasm = "build --release --target wasm32-unknown-unknown --locked --workspace --exclude instrumental-testing"
wasm-debug = "build --lib --target wasm32-unknown-unknown --locked --workspace --exclude instrumental-testing"
unit-test = "test --lib --workspace --exclude margined-protocol --exclude instrumental-testing"
integration-test = "test --test integration"
fmt-check = "fmt --all -- --check"
lint = "clippy -- -D warnings"
schema = "run schema"
coverage = "tarpaulin"

[target.wasm32-unknown-unknown]
rustflags = ["-C", "link-arg=-s"]
